MODEL:
  BACKBONE: 'darknet53'
  ANCHOR_SIZES: [32, 64, 128]
  ANCHOR_STRIDES: [8, 16, 32]
  USE_HIGHER_LEVELS: False
DATASETS:
  TRAIN: ['data/BOP_dataset/lm/test', ]
  VALID: ['data/BOP_dataset/lm/test']
  MESH_DIR: 'data/BOP_dataset/lm/models_eval'
  # TEST: './data/SwissCube_1.0/testing.txt'
  KEYPOINT_FILE: '.cache/lm_keypoints3d.json'
  KEYPOINT_TYPE: "fps_8"  # TODO: only support 8 vertices now, since it's hardcoded here
  OBJ_IDS: ["1"]
  TRAIN_SPLIT_FPATH: ".cache/lm_real_split.json"
  VAL_SPLIT_FPATH: ".cache/lm_real_split.json"
  MESH_DIAMETERS: [102.099]
  N_CLASS: 2
INPUT:
  INTERNAL_WIDTH: 640
  INTERNAL_HEIGHT: 480
  INTERNAL_K: [572.4114, 0, 325.2611, 0, 572.4114, 242.04899, 0, 0, 1]
SOLVER:
  IMS_PER_BATCH: 8
  # 
  BASE_LR: 0.01
  STEPS_PER_EPOCH: 10000
  MAX_ITER: 300000
  SCHEDULER_POLICY: 'multi_steps'
  SCHEDULER_PARAMS: {'steps': [200000, 270000], 'gamma': 0.1}
  # 
  LOSS_WEIGHT_CLS: 0.01
  LOSS_WEIGHT_REG: 0.1
  POSITIVE_LAMBDA: 1.0
  AUGMENTATION_SHIFT: 0.1
  AUGMENTATION_SCALE: 0.1
  AUGMENTATION_ROTATION: 45
TEST:
  IMS_PER_BATCH: 1
  CONFIDENCE_TH: 0.3
